joinzien/scarce-editions

README.md, contracts/Migrations.sol, contracts/scarce-edition.sol, migrations/1_initial_migration.js, package-lock.json, package.json, truffle-config.js
=> Add a very basic ERC721 mintable contract

.gitignore, package-lock.json, package.json, truffle-config.js
=> Deployment config

contracts/Migrations.sol, migrations/1_initial_migration.js, migrations/2_deploy_scarce_edition.js, package.json, truffle-config.js
=> Update the compiler version

.github/workflows/truffle.yml
=> Start to a GitHub action for running the Truffle unit tests

.github/workflows/truffle.yml
=> Fix test action yml

.github/workflows/linter.yml, .solhint.json, README.md, package-lock.json, package.json
=> Add Solidity linter

README.md
=> Update the recommended Node version

README.md
=> Update npm and node versions

.gitignore, README.md
=> Add MIT license badge

contracts/ScarceEdition.sol, package-lock.json, package.json, test/create.js
=> Add operator aqccount

.github/workflows/codeql-analysis.yml
=> Add CodeQL action

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
=> Admin updates

contracts/ScarceEdition.sol, test/batchCreate.js
* Does your submission pass tests?
* Have you linted your code locally prior to submission?
=> Add batch create function

.gitignore, package-lock.json, package.json, truffle-config.js
=> Add test coverage reporting

contracts/ScarceEdition.sol, hardhat.config.ts
-   Does your submission pass tests?
-- YES
-   Have you linted your code locally prior to submission?
-- YES
=> Update solidity version to match openZeppelin #41

package.json, test/sampleTests_BatchCreate.ts, test/sampleTests_Create.ts
-   Does your submission pass tests?
-- YES
-   Have you linted your code locally prior to submission?
-- YES
=> Add test only owner #35

package.json, test/sampleTests_BatchCreate.ts, test/sampleTests_Create.ts
-   Does your submission pass tests?
-- YES
-   Have you linted your code locally prior to submission?
-- YES
=> Add test batch # 36

test/sampleTests_BatchCreate.ts
-   Does your submission pass tests?
-- YES
-   Have you linted your code locally prior to submission?
-- YES
=> Add test batch

.github/workflows/hardhat.yml, .github/workflows/linter.yml
=> Rename the actions

.github/workflows/hardhat.yml, .github/workflows/linter.yml, documentation/develop.md
=> Switch to using node lts/fermium
